### ISSUE TITLE
Refactor CSVelte\Taster class

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#1]
There are loads of @todo tags inside the Taster class. Take a look at them and refactor. Many/most of the most expensive methods in this class are looping through the source data two or more times when they really only need to loop once. Also there are a lot of places where I do full foreach loops with all kinds of unnecessary variable assignments (that don't even end up being used) when I could just as easily run array_map or something similar and be done with it. 

I mainly created this issue just because I had never created an issue (not to my recollection anyway) on github and I wanted to get a feel for its issue tracker. Oh wow, here's a nifty tool...

**Tasks (pulled from @todo's within the file and its tests):**
- [ ] Either the taster class needs to be a singleton or there needs to be a way to set a default taster to use unless explicitly requested otherwise. The taste() function provides a convenient place to perform "should I use the default or was I passed an explicit taster?" functionality
- [x] There are a ton of improvements that could be made to this class. I'll do a refactor on this fella once I get at least one test passing for each of its public methods.
- [ ] Should I have a lickEscapeChar method? The python version doesn't have one. But then why does it even bother including one in its flavor class?
- [ ] Examine each of the public methods in this class and determine whether it makes sense to ask for the data as a param rather than just pulling it from source. I don't think it makes sense... it was just easier to write the methods that way during testing.
- [ ] ~~Should there be a lickEscapeChar method? the python module that inspired this library doesn't include one...~~ (duplicate)
- [ ] Implement a lickQuote method for when lickQuoteAndDelim method fails
- [ ] Replace code that uses this method with the replaceQuotedSpecialChars method instead. I think it's cleaner.
- [x] lickLineEndings This should throw an exception if it cannot determine the line ending or it should return a default char (PHP_EOL?)
- [x] I probably will make this method (lickLineEndings) protected when I'm done with testing
- [ ] If there is any way for this method (lickLineEndings) to fail (for instance if a file is totally empty or contains no line breaks), then it needs to throw a relevant TasterException
- [ ] Use replaceQuotedSpecialChars method rather than removeQuotedStrings() and then get rid of removeQuotedStrings method
- [ ] Get the Scrutinizer grade for the Taster class up to at the _very_ least, a C. Preferrably a B or even an A, but a C at minimum. (see: https://scrutinizer-ci.com/g/nozavroni/csvelte/code-structure/master/class/CSVelte%5CTaster). 
  - [ ] Reduce complexity of the class in general
    - [ ] Bring grade for `lickDelimiter` class up to at least a C by reducing complexity
    - [ ] Bring grade for `lickHeader` class up to at least a C by reducing complexity
  - [ ] Reduce class dependencies if possible (see coupling score on Scrutinizer)

**Comment by deni-zen** [comment]
I pulled this note from Reader's constructor's dockblock... 

```
     * @todo Taster is kind of a mess. It's not particularly easy to work with.
     *     Look at all this code I needed just to use it. Stupid. Time for a
     *     refactor... Maybe pass an argument to the lick() method to have it
     *     run lickHeader and set that value within the returned flavor's
     *     properties rather than all this silliness. Not to mention the oddness
     *     of setting a source in its constructor and then, inexplicably, still
     *     asking for a data sample in lickHeader. Very poor design. SMH at myself.
```

**Comment by deni-zen** [comment]
I actually did quite a bit of work on the Taster method already but the rest of this is going to have to wait until v0.2

**Comment by nozavroni** [comment]
I want to make the taster more configurable. You should be able to weight its decision-making if you want to. For instance... 

``` php
$in = Stream::open($filename, 'r+b');
$taster = new Taster($in);
// change taster's delimiter "preference"
$taster->setDelimPreference([';', "\t", ',', '|', '-']);
```
