### ISSUE TITLE
Need to add Roadmap and Changelog

### ISSUE THREAD

**Issue by nozavroni** [deni-zen/csvelte#117]
I could have sworn I already created a ticket for this but oh well. Before release v0.2 can go out, I need at the very least a CHANGELOG.md file in the project's topmost directory with README.md and LICENSE and all that. It would be nice to include a ROADMAP.md file as well... but not absolutely vital. 
- [x] Write CHANGELOG.md file in project's home directory
  - [ ] Would be nice to also have a changelog in RTD but not absolutely necessary, this can wait 
- [x] Write ROADMAP.md file in project's home directory
  - [ ] I make reference to a roadmap in RTD user's guide, so I need to add it there or remove the references to it. I have a page in one of my binders with a basic outline

Here is a list of all issues completed for version 0.2 milestone - https://github.com/nozavroni/csvelte/milestone/4?closed=1

See, I knew I had already created a ticket for this... https://github.com/nozavroni/csvelte/issues/72 and https://github.com/nozavroni/csvelte/issues/73
