### ISSUE TITLE
v0.0.1 checklist

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#33]
Put together a checklist containing everything you feel is necessary for this library's very first pre-release. I know that I want, at the very least, to be able to read and write well-formed CSV files and to be capable of dialect/flavor auto-detection at least 75% of the time. I think it's probably well above that already. I'm not going to require schemas (at least not beyond a rudimentary implementation) or any kind of CSVW compliance. Yet. 

Go through whichever of the following don't currently have an associated issue/ticket and create one, then put each item's ticket number before its description.

Note: Another name I was considering for the library was "PHabular" or "PHabulous" because it isn't necessarily only CSV. The scope of the library is more than just CSV import/export. It deals with all tabular data. Think about other names. 

**v0.0.1 Feature Checklist** 
- [x] CSVelte\Reader - line iterator class (should this be Parser? I don't think it should. Parser makes CSV sound like some complex format when it's literally the most stupid-simple pseudo-format I can think of)
- [x] CSVelte\Contract\Readable - To be readable by the Reader class, implement CSVelte\Contract\Readable. Write concrete implementations of the most common sources (file, stream, string...)
- [x] CSVelte\Writer - Capable of writing a line at a time or by accepting an iterable and writing a line for each iteration
- [x] CSVelte\Contract\Writable - To be writable by the Writer class, implement CSVelte\Contract\Writable. Write concrete implementations of the most common outputs (file, stream, string, stdout?)
- [x] CSVelte\Flavor - Simple class that dictates the "dialect" or formatting details of a particular file
- [x] CSVelte\Flavor* - Need concrete implementations of the most common dialects: Rfc4180 (Excel), ExcelTab, StandardCSV, StandardTSV, etc. (python's csv module has excel, excel-tab and unix dialects built-in)
- [x] CSVelte\Taster - Automatically detects dialect (tastes flavor) of a CSV data source, given a small sample
- [x] CSVelte\Reader\Row column iterator 

**v0.0.1 Bug Checklist** 

Coming soon... 

**v0.0.1 Task Checklist**
- [x] Write documentation, create PDF, text (markdown), and web versions of it (at github.io homepage)
- [x] Put together a script or find a service that will help you with deployments for consistency. I used to use Phing but I'm sure there are endless options for SaaS deployment nowadays
- [x] Update README document to tell users where they can find documentation and what the scope/aim of the library is.

**Comment by deni-zen** [comment]
This should actually be v0.1.0 and this is the first of 3 issues exactly like this... lol
