### ISSUE TITLE
Leftover from 0.1

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#47]
I would really like to just get a first version of this library out so rather than try to overhaul the entire underlying parsing/rendering system before v0.1 I have decided to, instead, limp on using the existing infrastructure so that I can push out a v0.1 and people can start using it WHILE I overhaul the underlying infrastructure... The following list is what I MUST have for v0.1: 
- [x] CSVelte\Reader - At least a way to loop over a CSV file and read each "cell"
  - [x] Implement filter and other callback methods (issue #55)
- [x] CSVelte\Writer - Accept an array or array of arrays and write it to an output source (generally a file). 
  - [ ] Writer needs to use the CSVelte\Table\Cell and it needs to properly quote values that contain special characters, escape quotes with either a quote or an escapeChar, etc.
- [x] CSVelte\Taster - A way to automatically detect CSV format (or flavor or dialect... whatever you want to call it). 
- [x] CSVelte Convenience Class - The CSVelte class will be used as a convenience adapter to simplify complex functionality. 
- [x] remove all currently unused code from this branch
- [x] remove all currently unused tests as well 
- [x] figure out which of the automated API doc generators you're going to use ([phpDocumentor](https://phpdoc.org/), [doxygen](http://www.stack.nl/~dimitri/doxygen/), [NaturalDocs](http://www.naturaldocs.org/), [apiGen](http://www.apigen.org/), [slate](https://github.com/lord/slate), or [some other one](https://en.wikipedia.org/wiki/Comparison_of_documentation_generators)
- [x] configure travis
  - [x] add .travis.yml file to top-level directory
  - [x] configure existing unit tests to work with travis
  - [x] figure out which versions of PHP you want CSVelte to support (php7? php5.3+ or php5.4+?)
  - [x] make sure to have API docs re-generated
- [x] Finish guide-style documentation on github pages 
- [x] Fully docblock everything so that API docs are actually useful 
- [ ] Write tests for each example you have in your guide-style documentation 
- [x] ~~Write docs that are kind of in between auto-generated API docs and guide-style docs. Basically, just take the most common classes and document each of their public methods. For instance, write a page for CSVelte\Reader, one for CSVelte\Writer, one for CSVelte, etc.~~ Not doing this
## Currently open tickets
- [ ] #1 Refactor Taster class 
- [x] #2 More thorough unit testing 
- [ ] #3 Remove sample CSV files from git repo 
- [ ] #8 Refactor flavor class 
- [x] #12 Write CSV data source classes 
- [ ] #19 Writer class(es) 
- [ ] #22 De-facto CSV standard 
- [ ] #30 Project home page
- [x] #33 Original v0.1 checklist 
- [x] #42 Move Row classes into table namespace
- [ ] #45 Reader is buggy 
- [ ] #51 Create API docs 
- [ ] #52 Dependency handling for non composer users 
- [x] #53 Write tests for examples/docs 
- [ ] #55 Add filter and other functions to reader 
- [x] #57 Figure out delivery process 
- [ ] #62 Integrate with Travis-CI 
- [x] #67 ReadTheDocs Integration and docs 
- [x] #68 Delete old branches 
- [ ] #69? Alternate PHP support 
- [x] #70 Integrate with Scrutinizer 
- [ ] #71 Testing/CI Code coverage inspiration 
- [x] #73 Create roadmap

**Comment by deni-zen** [comment]
I'm going to branch off the branch I'm using right now for my v0.0.1 push
