### ISSUE TITLE
ReadTheDocs updates for v0.2

### ISSUE THREAD

**Issue by nozavroni** [deni-zen/csvelte#87]
### Updates for v0.2

All the changes I've made for v0.2 need to be documented and/or the documentation needs to be updated. There are also a few features/concepts that were included in v0.1 that just never got documented. Finally, the section called "tutorials" still says coming soon, so if you have time to dump even a single tutorial in there, it would look a million times better. 
- [x] Documentation for #98 - Reader and Writer with new IO\File class 
- [x] Documentation for #97 - Update documentation related to Input/Output 
- [x] Documentation for #92 - CSVelte\CSVelte facade/factory methods were left out of v0.1 docs 
- [x] Documentation for #77 - New SplFileObject File class
- [x] Documentation for #54 - Arrays in place of Flavor 
- [x] Documentation for #64 - If I end up implementing CSV output, need to document it
- [x] Re-generate API docs for v0.2 and decide on API docs dir structure - see #51 
- [ ] ReadTheDocs improvements carried over from last release - see #95 
- [ ] Put together a glossary of terms so that things like "flavor" and "taster" can just link to the glossary rather than having to redefine them over and over again
- [ ] Figure out how to markup the docs to get a proper index at the end 
- [ ] Add at least one tutorial to the tutorials section
- [x] phpcsv.com doesn't have any links to the RTD documentation (csvelte.phpcsv.com)

After you fix the lickHeader method (make it use the sample data passed to taster's constructor) add this section back to the taster reference guide.

```
Analyzing data for header row
=============================

CSV files often use the first row of their dataset as a list of human-readable column names called a header row. The ``CSVelte\Taster`` object can *usually* determine whether a dataset contains a header row but just as with the Flavor detection, it can only guess. If it fails, it issues a similar exception to the one(s) issued by the ``CSVelte\Taster::lick()`` method.

.. code-block:: php 

    <?php 
    try {
        $csv = new CSVelte\Input\File('./import/data.csv');
        $taster = new CSVelte\Taster($csv);
        if ($taster->lickHeader() {

        })
    } catch (CSVelte\Exception\TasterException $e) {

    }

```

**Comment by nozavroni** [comment]
I'm going to just call this finished. The docs are a living document they will round out organically.
